// <auto-generated />
using System;
using HardwareMonitoringServer.DbSetting;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HardwareMonitoringServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("ComputerModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Computers");
                });

            modelBuilder.Entity("HardwareMonitoringServer.Models.SensorModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SensorTypeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SystemModelId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SystemModelId1")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("SystemModelId1");

                    b.ToTable("Sensors");
                });

            modelBuilder.Entity("HardwareMonitoringServer.Models.SystemModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComputerModelId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ComputerModelId1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ComputerModelId1");

                    b.ToTable("Systems");
                });

            modelBuilder.Entity("HardwareMonitoringServer.Models.SensorModel", b =>
                {
                    b.HasOne("HardwareMonitoringServer.Models.SystemModel", null)
                        .WithMany("Sensors")
                        .HasForeignKey("SystemModelId1");
                });

            modelBuilder.Entity("HardwareMonitoringServer.Models.SystemModel", b =>
                {
                    b.HasOne("ComputerModel", null)
                        .WithMany("Systems")
                        .HasForeignKey("ComputerModelId1");
                });

            modelBuilder.Entity("ComputerModel", b =>
                {
                    b.Navigation("Systems");
                });

            modelBuilder.Entity("HardwareMonitoringServer.Models.SystemModel", b =>
                {
                    b.Navigation("Sensors");
                });
#pragma warning restore 612, 618
        }
    }
}
